# ---------------------------------------------------
# REQUIRED - INPUTS - List all inputs to SPANet here.
# ---------------------------------------------------
INPUTS:
  # -----------------------------------------------------------------------------
  # REQUIRED - SEQUENTIAL - inputs which can have an arbitrary number of vectors.
  # -----------------------------------------------------------------------------
  SEQUENTIAL:
    Source:
#      mass: log_normalize
      energy: log_normalize
      pt: log_normalize
      eta: normalize
      phi: normalize_uniform
      btag: none
      isLepton: none
      charge: none

#      mass: log_normalize
#      pt: log_normalize
#      eta: normalize
#      phi: normalize_uniform
#      btag: none
#      isLepton: none
#      charge: none

  # ---------------------------------------------------------------------
  # REQUIRED - GLOBAL - inputs which will have a single vector per event.
  # ---------------------------------------------------------------------
  GLOBAL:
    Conditions:
#      met: log_normalize
#      met_phi: normalize

      met: log_normalize
      met_phi: normalize
      nLepton: none
      nbJet: none
      nJet: none
      HT: log_normalize
      HT_lep: log_normalize
      M_all: log_normalize
      M_leps: log_normalize
      M_bjets: log_normalize


# ----------------------------------------------------------------------
# REQUIRED - EVENT - Complete list of resonance particles and daughters.
# ----------------------------------------------------------------------
EVENT:
  TT2L:
    t1:
      - b
      - l+
    t2:
      - b
      - l-

# ---------------------------------------------------------
# REQUIRED KEY - PERMUTATIONS - List of valid permutations.
# ---------------------------------------------------------
PERMUTATIONS:
  TT2L:
    - []

# ------------------------------------------------------------------------------
# REQUIRED - REGRESSIONS - List of desired features to regress from observables.
# ------------------------------------------------------------------------------
REGRESSIONS:
  EVENT: []


# -----------------------------------------------------------------------------
# REQUIRED - REGRESSIONS - List of desired classes to predict from observables.
# -----------------------------------------------------------------------------
CLASSIFICATIONS:
  EVENT:
    - signal

CLASSLABEL:
  EVENT:
    signal:
      - [ TT ]

PARTICLE_PROPERTIES:
#  - Mass
  - Energy
  - Spin
  - nProduct_BJet
  - nProduct_Jet
  - nProduct_Lepton
  - Product_LeptonCharge

GENERATIONS:
  Conditions:
    - met
    - met_phi
  GlobalTargets: []

  Neutrinos:
#    mass: empty
    pt: log_normalize
    eta: normalize
    phi: normalize_uniform
#    btag: empty
#    isLepton: empty
#    charge: empty