platform:
  data_parquet_dir: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/nu2flow/mg5_test/"
  number_of_workers: 4
  resources_per_worker: {
    "CPU": 30,
    "GPU": 1,
  }
  batch_size: 4096
  prefetch_batches: 2
  use_gpu: true

options:
  default: ../../share/options/options.yaml

  # For prediction Only
  prediction:
    # The directory where the prediction data is saved
    output_dir: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/predicts.nu2flow/"
    # The filename of the prediction data
    filename: "prediction-mg5-20250812-ema.pt"

    extra_save:
      - EXTRA/num_bjet
      - EXTRA/t1/b/pt
      - EXTRA/t1/b/eta
      - EXTRA/t1/b/phi
      - EXTRA/t1/b/energy
      - EXTRA/t1/l/pt
      - EXTRA/t1/l/eta
      - EXTRA/t1/l/phi
      - EXTRA/t1/l/energy
      - EXTRA/t2/b/pt
      - EXTRA/t2/b/eta
      - EXTRA/t2/b/phi
      - EXTRA/t2/b/energy
      - EXTRA/t2/l/pt
      - EXTRA/t2/l/eta
      - EXTRA/t2/l/phi
      - EXTRA/t2/l/energy
      - EXTRA/truth_t1/t/pt
      - EXTRA/truth_t1/t/eta
      - EXTRA/truth_t1/t/phi
      - EXTRA/truth_t1/t/mass
      - EXTRA/truth_t1/W/pt
      - EXTRA/truth_t1/W/eta
      - EXTRA/truth_t1/W/phi
      - EXTRA/truth_t1/W/mass
      - EXTRA/truth_t1/l/pt
      - EXTRA/truth_t1/l/eta
      - EXTRA/truth_t1/l/phi
      - EXTRA/truth_t1/l/mass
      - EXTRA/truth_t2/t/pt
      - EXTRA/truth_t2/t/eta
      - EXTRA/truth_t2/t/phi
      - EXTRA/truth_t2/t/mass
      - EXTRA/truth_t2/W/pt
      - EXTRA/truth_t2/W/eta
      - EXTRA/truth_t2/W/phi
      - EXTRA/truth_t2/W/mass
      - EXTRA/truth_t2/l/pt
      - EXTRA/truth_t2/l/eta
      - EXTRA/truth_t2/l/phi
      - EXTRA/truth_t2/l/mass

  Training:
    total_epochs: 500
    epochs: 250
    model_checkpoint_save_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.nu2flow/mg5"
    model_checkpoint_load_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.nu2flow/mg5/epoch=246_train=0.5459_val=0.5564.ckpt"
    pretrain_model_load_path: null
    # pretrain_model_load_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.full/best_epoch=3.ckpt"

    diffusion_every_n_epochs: 10 # how often to run diffusion
    diffusion_every_n_steps: 1 # how often to run diffusion inside the valid epoch

    learning_rate: &lr 0.00075
    learning_rate_body: &lr_body 0.00075
    weight_decay: &wd 0.001
    Components:
      GlobalEmbedding:
        learning_rate: *lr_body
        weight_decay: *wd
        optimizer_type: "AdamW"
      PET:
        learning_rate: *lr_body
        weight_decay: *wd
        optimizer_type: "AdamW"
      ObjectEncoder:
        learning_rate: *lr_body
        weight_decay: *wd
        optimizer_type: "AdamW"
      Classification:
        include: false
      Regression:
        include: false
      Assignment:
        include: false
      Segmentation:
        include: false
      GlobalGeneration:
        include: false
      ReconGeneration:
        include: false
      TruthGeneration:
        include: true
        warm_up: true
        learning_rate: *lr
        weight_decay: *wd
        optimizer_type: "AdamW"
        diffusion_steps: 300

    EMA:
      enable: true               # Enable or disable EMA
      decay: 0.999               # EMA decay rate
      start_epoch: 0             # Start updating EMA after this epoch
      update_every_n_steps: 1    # Update EMA every N steps

      replace_model_after_load: true    # After loading checkpoint, copy EMA weights into model
      replace_model_at_end: false         # At training end, copy EMA weights into model (will not save EMA weights)


  Dataset:
    dataset_limit: 1.0
    normalization_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/nu2flow/mg5_train/normalization.pt"
    train_validation_split: 0.75


#  Metrics:
#    Generation-Binning:
#      "neutrino-log_pt": [ 50, -4, 4 ]
#      "neutrino-eta": [ 50, -4, 4 ]
#      "neutrino-phi": [ 50, -4, 4 ]


network:
  default: ../../share/pretrain-config/network-20M.yaml

  Body:
    PET:
      feature_drop: 0.0
  ReconGeneration:
    feature_drop: 0.0
  TruthGeneration:
    feature_drop: 0.0

event_info:
  default: configs/event_info.yaml

resonance:
  default: ../../share/resonance/standard_model.yaml
