platform:
  data_parquet_dir: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/nu2flow/mg5_test/"
  number_of_workers: 4
  resources_per_worker: {
    "CPU": 30,
    "GPU": 1,
  }
  batch_size: 4096
  prefetch_batches: 2
  use_gpu: true

options:
  default: configs/options.yaml

  # For prediction Only
  prediction:
    # The directory where the prediction data is saved
    output_dir: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/predicts.nu2flow/"
    # The filename of the prediction data
    filename: "prediction-mg5-300.pretrain.pt"

    extra_save:
      - EXTRA/num_bjet
      - EXTRA/t1/b/pt
      - EXTRA/t1/b/eta
      - EXTRA/t1/b/phi
      - EXTRA/t1/b/energy
      - EXTRA/t1/l/pt
      - EXTRA/t1/l/eta
      - EXTRA/t1/l/phi
      - EXTRA/t1/l/energy
      - EXTRA/t2/b/pt
      - EXTRA/t2/b/eta
      - EXTRA/t2/b/phi
      - EXTRA/t2/b/energy
      - EXTRA/t2/l/pt
      - EXTRA/t2/l/eta
      - EXTRA/t2/l/phi
      - EXTRA/t2/l/energy
      - EXTRA/truth_t1/t/pt
      - EXTRA/truth_t1/t/eta
      - EXTRA/truth_t1/t/phi
      - EXTRA/truth_t1/t/mass
      - EXTRA/truth_t1/W/pt
      - EXTRA/truth_t1/W/eta
      - EXTRA/truth_t1/W/phi
      - EXTRA/truth_t1/W/mass
      - EXTRA/truth_t1/l/pt
      - EXTRA/truth_t1/l/eta
      - EXTRA/truth_t1/l/phi
      - EXTRA/truth_t1/l/mass
      - EXTRA/truth_t2/t/pt
      - EXTRA/truth_t2/t/eta
      - EXTRA/truth_t2/t/phi
      - EXTRA/truth_t2/t/mass
      - EXTRA/truth_t2/W/pt
      - EXTRA/truth_t2/W/eta
      - EXTRA/truth_t2/W/phi
      - EXTRA/truth_t2/W/mass
      - EXTRA/truth_t2/l/pt
      - EXTRA/truth_t2/l/eta
      - EXTRA/truth_t2/l/phi
      - EXTRA/truth_t2/l/mass


  Training:
    total_epochs: 500
    epochs: 500
    model_checkpoint_save_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.nu2flow/mg5"
    model_checkpoint_load_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.nu2flow/mg5/pretrain.425.ckpt"
    pretrain_model_load_path: null
#    pretrain_model_load_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.full.diffusion/vanilla.1.ckpt"

    diffusion_every_n_epochs: 50 # how often to run diffusion
    diffusion_every_n_steps: 1 # how often to run diffusion inside the valid epoch

    learning_rate: &lr 0.0005
    learning_rate_body: &lr_body 0.00005
    weight_decay: &wd 0.01
    Components:
      GlobalEmbedding:
        learning_rate: *lr_body
        weight_decay: *wd
        optimizer_type: "AdamW"
      PET:
        learning_rate: *lr_body
        weight_decay: *wd
        optimizer_type: "AdamW"
      ObjectEncoder:
        learning_rate: *lr_body
        weight_decay: *wd
        optimizer_type: "AdamW"
      Classification:
        include: false
        include_cross_term: false
      Regression:
        include: false
      Assignment:
        include: false
        warm_up: true
        learning_rate: *lr
        weight_decay: *wd
        optimizer_type: "AdamW"
      GlobalGeneration:
        include: false
      ReconGeneration:
        include: false
      TruthGeneration:
        include: true
        warm_up: true
        learning_rate: *lr
        weight_decay: *wd
        optimizer_type: "AdamW"
        diffusion_steps: 300

    EarlyStopping:
      patience: 100
      min_delta: 0.0
      monitor: "val/generation-truth"
      mode: "min"
      verbose: true

  Dataset:
    dataset_limit: 1.0
#    normalization_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/nu2flow/mg5_train/normalization.pt"
    normalization_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/run.20250505.135M/normalization.pt"
    #    balance_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/SPANet/ttbar_semi_leptonic/train/normalization.pt"
    val_split: [ 0.75, 1.0 ]


network:
#  default: configs/model.yaml
  #  default: configs/model_large.yaml
  default: configs/pretrain.yaml

  Body:
    PET:
      feature_drop: 0.0
  ReconGeneration:
    feature_drop: 0.0
  TruthGeneration:
    feature_drop: 0.0
  # overwrites
  # ...

event_info:
  default: configs/event_info.yaml

  # overwrites
  # ...

resonance:
  default: configs/resonance.yaml

  # overwrites
  # ...