platform:
  data_parquet_dir: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/nu2flow/mg5_train"
  number_of_workers: 16
  resources_per_worker: {
    "CPU": 30,
    "GPU": 1,
  }
  batch_size: 2048
  prefetch_batches: 2
  use_gpu: true

wandb:
  project: "nu2flow-tt2l"
  entity: "ytchou97-university-of-washington"
  name: "tt2l"
  tags: [ "Pretrain", "Parquet", "NERSC", "TT2L", "Neutrinos" ]

options:
  default: configs/options.yaml

  Training:
    total_epochs: 100
    epochs: 100
    model_checkpoint_save_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.nu2flow/mg5"
#    model_checkpoint_load_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.SPANet/TT1L/best_epoch=49-v1.ckpt"
    pretrain_model_load_path: null
    #    pretrain_model_load_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.full/best_epoch=3.ckpt"

    diffusion_every_n_epochs: 10 # how often to run diffusion
    diffusion_every_n_steps: 1 # how often to run diffusion inside the valid epoch

    learning_rate: &lr 0.0005
    learning_rate_body: &lr_body 0.0005
    weight_decay: &wd 0.01
    Components:
      GlobalEmbedding:
        learning_rate: *lr_body
        weight_decay: *wd
        optimizer_type: "AdamW"
      PET:
        learning_rate: *lr_body
        weight_decay: *wd
        optimizer_type: "AdamW"
      ObjectEncoder:
        learning_rate: *lr_body
        weight_decay: *wd
        optimizer_type: "AdamW"
      Classification:
        include: false
        warm_up: true
        learning_rate: *lr
        weight_decay: *wd
        optimizer_type: "AdamW"
      Regression:
        include: false
        warm_up: true
        learning_rate: *lr
        weight_decay: *wd
        optimizer_type: "AdamW"
      Assignment:
        include: false
        warm_up: true
        learning_rate: *lr
        weight_decay: *wd
        optimizer_type: "AdamW"
      GlobalGeneration:
        include: true
        warm_up: true
        learning_rate: *lr
        weight_decay: *wd
      EventGeneration:
        include: true
        warm_up: true
        generate_point_cloud: false
        generate_neutrino: true
        learning_rate: *lr
        weight_decay: *wd

  Dataset:
    dataset_limit: 1.0
    normalization_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/nu2flow/mg5_train/normalization.pt"
    #    normalization_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/run.20250420.full/normalization.pt"
    #    balance_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/SPANet/ttbar_semi_leptonic/train/normalization.pt"
    train_validation_split: 0.75

  Metrics:
    Generation-Binning:
      "neutrino-log_pt": [ 50, -4, 4 ]
      "neutrino-eta": [ 50, -4, 4 ]
      "neutrino-phi": [ 50, -4, 4 ]


network:
  default: configs/model.yaml
  #  default: configs/model_large.yaml
  #  default: configs/pretrain.yaml

  # overwrites
  # ...

event_info:
  default: configs/event_info.yaml

  # overwrites
  # ...

resonance:
  default: configs/resonance.yaml

  # overwrites
  # ...