platform:
  data_parquet_dir: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/nu2flow/mg5_train"
  number_of_workers: 16
  resources_per_worker: {
    "CPU": 30,
    "GPU": 1,
  }
  batch_size: 2048
  prefetch_batches: 2
  use_gpu: true

logger:
  wandb:
    project: "nu2flow-tt2l"
    entity: "ytchou97-university-of-washington"
    name: &logger_name "tt2l-20M"
    tags: [ "NERSC", "TT2L", "Neutrinos" ]
    simplified: false
  local:
    save_dir: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/logs"
    name: *logger_name
    version: "2025-08-12"


options:
  default: ../../share/options/options.yaml

  Training:
    total_epochs: 500
    epochs: 500
    model_checkpoint_save_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.nu2flow/mg5"
    #    model_checkpoint_load_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.SPANet/TT1L/best_epoch=49-v1.ckpt"
    pretrain_model_load_path: /global/cfs/cdirs/m5019/avencast/Checkpoints/EveNet-20M-20250811-train=2.6601_val=2.6352.ckpt
#        pretrain_model_load_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.full/best_epoch=3.ckpt"

    diffusion_every_n_epochs: 50 # how often to run diffusion
    diffusion_every_n_steps: 1 # how often to run diffusion inside the valid epoch

    learning_rate: &lr 0.00025
    learning_rate_body: &lr_body 0.00025
    weight_decay: &wd 0.01
    Components:
      GlobalEmbedding:
        learning_rate: *lr_body
        weight_decay: *wd
        optimizer_type: "AdamW"
      PET:
        learning_rate: *lr_body
        weight_decay: *wd
        optimizer_type: "AdamW"
      ObjectEncoder:
        learning_rate: *lr_body
        weight_decay: *wd
        optimizer_type: "AdamW"
      Classification:
        include: false
      Regression:
        include: false
      Assignment:
        include: false
      Segmentation:
        include: false
      GlobalGeneration:
        include: false
      ReconGeneration:
        include: false
      TruthGeneration:
        include: true
        warm_up: true
        learning_rate: *lr
        weight_decay: *wd
        optimizer_type: "AdamW"
        diffusion_steps: 200

    EarlyStopping:
      patience: 200
      min_delta: 0.0
      monitor: "val/generation-truth"
      mode: "min"
      verbose: true

    EMA:
      enable: true               # Enable or disable EMA
      decay: 0.999               # EMA decay rate
      start_epoch: 0             # Start updating EMA after this epoch
      update_every_n_steps: 1    # Update EMA every N steps

      replace_model_after_load: true    # After loading checkpoint, copy EMA weights into model
      replace_model_at_end: false         # At training end, copy EMA weights into model (will not save EMA weights)


  Dataset:
    dataset_limit: 1.0
    normalization_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/nu2flow/mg5_train/normalization.pt"
    val_split: [ 0.75, 1.0 ]


network:
  default: ../../share/pretrain-config/network-20M.yaml

  Body:
    PET:
      feature_drop: 0.0
  ReconGeneration:
    feature_drop: 0.0
  TruthGeneration:
    feature_drop: 0.0

event_info:
  default: configs/event_info.yaml

resonance:
  default: ../../share/resonance/standard_model.yaml
