event_info:
  default: event_info_cls.yaml
network:
  default: network.yaml
options:
  Dataset:
    dataset_limit: 1.0
    normalization_file: /pscratch/sd/t/tihsu/database/EveNet-AnomalyDetection-CMSOpenData-ip3d-simple/EveNetInput_hybrid/SR/normalization.pt
  ProgressiveTraining:
    stages:
    - epoch_ratio: 1.0
      loss_weights:
        assignment:
        - 0.0
        - 0.0
        classification:
        - 1.0
        - 1.0
        classification-noised:
        - 0.0
        - 0.0
        generation:
        - 0.0
        - 0.0
        generation-recon:
        - 0.0
        - 0.0
        regression:
        - 0.0
        - 0.0
      name: full_training
      train_parameters:
        ema_decay:
        - 0.999
        - 0.999
        noise_prob:
        - 0.0
        - 0.0
        reco_attn_mask:
        - 0.0
        - 0.0
      transition_ratio: 0.0
  Training:
    Components:
      Classification:
        include: true
    epochs: 300
    model_checkpoint_load_path: null
    model_checkpoint_save_path: /pscratch/sd/t/tihsu/database/EveNet-AnomalyDetection-CMSOpenData-ip3d-simple/EveNetInput_hybrid/SR/model_checkpoint
    patience: 30
    pretrain_model_load_path: /pscratch/sd/t/tihsu/database/pretrain-wp/pretrain_2025May28.ckpt
  default: options_cls.yaml
platform:
  batch_size: 2048
  data_parquet_dir: /pscratch/sd/t/tihsu/database/EveNet-AnomalyDetection-CMSOpenData-ip3d-simple/EveNetInput_hybrid/SR/
  number_of_workers: 1
  prefetch_batches: 2
  resources_per_worker:
    CPU: 3
    GPU: 1
resonance:
  default: resonance.yaml
wandb:
  entity: ytchou97-university-of-washington
  name: toy-model
  project: anomaly-detection-cls
  run_name: CMS-Data-Classification-Training_pretrain_pretrain_pretrain
  tags:
  - Pretrain
  - Parquet
  - NERSC
  - Multi-Node
