event_info:
  default: event_info.yaml
network:
  default: network.yaml
options:
  Dataset:
    dataset_limit: 1.0
    normalization_file: /pscratch/sd/t/tihsu/database/EveNet-AnomalyDetection-CMSOpenData-ip3d-paper-pretrain-EPS-v6/EveNetInput/SB/normalization.pt
  ProgressiveTraining:
    stages:
    - epoch_ratio: 1.0
      loss_weights:
        assignment:
        - 0.0
        - 0.0
        classification:
        - 0.0
        - 0.0
        classification-noised:
        - 0.0
        - 0.0
        generation:
        - 1.0
        - 1.0
        generation-recon:
        - 1.0
        - 1.0
        regression:
        - 0.0
        - 0.0
      name: full_training
      train_parameters:
        ema_decay:
        - 0.999
        - 0.999
        noise_prob:
        - 1.0
        - 1.0
        reco_attn_mask:
        - 0.0
        - 0.0
      transition_ratio: 0.0
  Training:
    Components:
      GlobalGeneration:
        include: true
      ReconGeneration:
        include: true
    epochs: 1000
    model_checkpoint_load_path: null
    model_checkpoint_save_path: /pscratch/sd/t/tihsu/database/EveNet-AnomalyDetection-CMSOpenData-ip3d-paper-pretrain-EPS-v6/EveNetInput/SB/model_checkpoint
    patience: 1000
    pretrain_model_load_path: /global/cfs/cdirs/m5019/Checkpoints/nominal.epoch9.ckpt
  default: options.yaml
platform:
  batch_size: 4096
  data_parquet_dir: /pscratch/sd/t/tihsu/database/EveNet-AnomalyDetection-CMSOpenData-ip3d-paper-pretrain-EPS-v6/EveNetInput/SB
  number_of_workers: 2
  prefetch_batches: 2
  resources_per_worker:
    CPU: 28
    GPU: 1
resonance:
  default: resonance.yaml
wandb:
  entity: ytchou97-university-of-washington
  name: toy-model
  project: anomaly-detection
  run_name: paper-EPS-pretrain
  tags:
  - Pretrain
  - Parquet
  - NERSC
  - Multi-Node
