platform:
  data_parquet_dir: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/SPANet/ttbar_semi_leptonic/train/"
  number_of_workers: 16
  resources_per_worker: {
    "CPU": 30,
    "GPU": 1,
  }
  batch_size: 2048
  prefetch_batches: 2
  use_gpu: true

wandb:
  project: "spanet-tt1l"
  entity: "ytchou97-university-of-washington"
  name: "tt1l"
  tags: [ "Pretrain", "Parquet", "NERSC", "TT1L", "PreTrain" ]

options:
  default: configs/options.yaml

  Training:
    total_epochs: 50
    epochs: 50
    model_checkpoint_save_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.SPANet/TT1L"
#    model_checkpoint_load_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.SPANet/TT1L/best_epoch=5-pretrain-1.ckpt"
    #    pretrain_model_load_path: null
    pretrain_model_load_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.full/best_epoch=3.ckpt"

    learning_rate: &lr 0.001
    learning_rate_body: &lr_body 0.000075
    weight_decay: &wd 0.001
    Components:
      GlobalEmbedding:
        learning_rate: *lr_body
        weight_decay: *wd
        optimizer_type: "AdamW"
      PET:
        learning_rate: *lr_body
        weight_decay: *wd
        optimizer_type: "AdamW"
      ObjectEncoder:
        learning_rate: *lr_body
        weight_decay: *wd
        optimizer_type: "AdamW"
      Classification:
        include: false
        warm_up: true
        learning_rate: *lr
        weight_decay: *wd
        optimizer_type: "AdamW"
      Regression:
        include: false
        warm_up: true
        learning_rate: *lr
        weight_decay: *wd
        optimizer_type: "AdamW"
      Assignment:
        include: true
        warm_up: true
        learning_rate: *lr
        weight_decay: *wd
        optimizer_type: "AdamW"
        assignment_loss_scale: 10.0
        detection_loss_scale: 0.0
      GlobalGeneration:
        include: false
      EventGeneration:
        include: false

  Dataset:
    dataset_limit: 1.0
#    normalization_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/SPANet/ttbar_semi_leptonic/train/normalization.pt"
    normalization_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/run.20250420.full/normalization.pt"
    train_validation_split: 0.75

network:
  #  default: configs/model.yaml
  #  default: configs/model_large.yaml
  default: configs/pretrain.yaml

  # overwrites
  # ...

event_info:
  default: configs/event_info.yaml

  # overwrites
  # ...

resonance:
  default: configs/resonance.yaml

  # overwrites
  # ...