platform:
  data_parquet_dir: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/run.20250409.tiny"
  number_of_workers: 16
  resources_per_worker: {
    "CPU": 30,
    "GPU": 1,
  }
  batch_size: 1024
  prefetch_batches: 2

wandb:
  project: "Pretrain"
  entity: "ytchou97-university-of-washington"
  name: "Pretrain"
  tags: [ "Pretrain", "Parquet", "NERSC", "Multi-Node" ]

options:
  default: options/options.yaml

  # overwrites
  Training:
    epochs: 20
    model_checkpoint_save_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints"
    model_checkpoint_load_path: null

    pretrain_model_load_path: null

    Components:
      Classification:
        include: false

      Regression:
        include: false

      Assignment:
        include: true
#        learning_rate: 0.00003
        warm_up: true

      GlobalGeneration:
        include: false

      EventGeneration:
        include: false

    ProgressiveTraining:
      - name: "assignment"
        epoch_ratio: 1.0
        components:
          - body
          - object_encoder
          - assignment
#          - classification
#      - name: "finetune"
#        epoch_ratio: 0.3
#        components:
#          - body
#          - object_encoder
#          - classification
#          - assignment

  Dataset:
    dataset_limit: 1.0
    normalization_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/run.20250409.tiny/normalization.pt"

network:
  default: network/pretrain.yaml

  # overwrites
  # ...

event_info:
  default: event_info/multi_process.yaml

  # overwrites
  # ...

resonance:
  default: resonance/standard_model.yaml

  # overwrites
  # ...