platform:
  data_parquet_dir: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/run.20250403"
  number_of_workers: 16
  resources_per_worker: {
    "CPU": 30,
    "GPU": 1,
  }
  batch_size: 4096
  prefetch_batches: 5

#platform:
#  data_parquet_dir: "/Users/avencastmini/PycharmProjects/EveNet/workspace/test_data/test_output"
#  number_of_workers: 1
#  resources_per_worker: {
#    "CPU": 1,
#    "GPU": 0,
#  }
#  batch_size: 256
#  prefetch_batches: 1

wandb:
  project: "Pretrain"
  entity: "ytchou97-university-of-washington"
  name: "Pretrain"
  tags: [ "Pretrain", "Parquet", "NERSC", "Multi-Node" ]

options:
  include: options/options.yaml

#  # overwrites
#  Training:
#    epochs: 1
#  Dataset:
#    balance_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/normalization_files/PreTrain_balance.pkl"
#    normalization_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/normalization_files/PreTrain_norm.pkl"

event_info:
  include: event_info/multi_process.yaml

  # overwrites
  # ...

resonance:
  include: resonance/standard_model.yaml

  # overwrites
  # ...