platform:
  data_parquet_dir: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/run.20250403"
  number_of_workers: 16
  resources_per_worker: {
    "CPU": 30,
    "GPU": 1,
  }
  batch_size: 4096
  prefetch_batches: 5

options:
  include: options/options.yaml

  # overwrites
  Training:
    epochs: 5

event_info:
  include: event_info/multi_process.yaml

  # overwrites
  # ...

resonance:
  include: resonance/standard_model.yaml

  # overwrites
  # ...