platform:
  data_parquet_dir: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/run.20250404"
  number_of_workers: 16
  resources_per_worker: {
    "CPU": 30,
    "GPU": 1,
  }
  batch_size: 4096
  prefetch_batches: 5


wandb:
  project: "Pretrain"
  entity: "ytchou97-university-of-washington"
  name: "Pretrain"
  tags: [ "Pretrain", "Parquet", "NERSC", "Multi-Node" ]

options:
  default: options/options.yaml

  # overwrites
  Training:
    epochs: 5
    classification_loss_scale: 1.0
    regression_loss_scale: 0.0
    feature_generation_loss_scale: 0.0
    assignment_loss_scale: 0.0
  Dataset:
    normalization_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/run.20250404/normalization.pt"

network:
  default: network/pretrain.yaml

  # overwrites
  # ...

event_info:
  default: event_info/multi_process.yaml

  # overwrites
  # ...

resonance:
  default: resonance/standard_model.yaml

  # overwrites
  # ...