platform:
  data_parquet_dir: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/run.20250505.135M"
  number_of_workers: 4
  resources_per_worker: {
    "CPU": 30,
    "GPU": 1,
  }
  batch_size: 256
  prefetch_batches: 2

  mixed_precision: false

wandb:
  project: "Pretrain"
  entity: "ytchou97-university-of-washington"
  name: "Pretrain"
  tags: [ "Pretrain", "NERSC", "Multi-Node", "135M", "Diffusion", "mix-precision" ]

options:
  default: options/options.yaml

  Training:
    total_epochs: 10
    epochs: 2
    model_checkpoint_save_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.full.diffusion"
#    model_checkpoint_load_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints.full.diffusion/best_epoch=3-v1.ckpt"
    pretrain_model_load_path: null

    diffusion_every_n_epochs: 1 # how often to run diffusion
    diffusion_every_n_steps: 1000 # how often to run diffusion inside the valid epoch

    learning_rate: &lr 0.000015
    weight_decay: &wd 0.0015
    Components:
      GlobalEmbedding:
        learning_rate: *lr
        weight_decay: *wd
      PET:
        learning_rate: *lr
        weight_decay: *wd
      ObjectEncoder:
        learning_rate: *lr
        weight_decay: *wd
      Classification:
        include: true
        warm_up: true
        learning_rate: *lr
        weight_decay: *wd
      Regression:
        include: false
        learning_rate: *lr
        weight_decay: *wd
      Assignment:
        include: true
        warm_up: true
        learning_rate: *lr
        weight_decay: *wd
      GlobalGeneration:
        include: true
        warm_up: true
        learning_rate: *lr
        weight_decay: *wd
      EventGeneration:
        include: true
        warm_up: true
        generate_point_cloud: true
        generate_neutrino: true
        learning_rate: *lr
        weight_decay: *wd

    ProgressiveTraining:
      - name: "everything"
        epoch_ratio: 1.0
        components:
          - body
          - object_encoder
          - assignment
          - classification
          - generation

    FAMO:
      turn_on: false
      detailed_loss: false
      detailed_loss_list:
        - classification
        - generation-global
        - generation-event
        - generation-invisible
        - assignment
        - detection
      logits_bound: 0.5
      lr: 0.025

  Dataset:
    dataset_limit: 1.0
    normalization_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/run.20250505.135M/normalization.pt"
    val_split: [ 0.7, 1.0 ]

  Metrics:
    Generation-Binning:
      "global-HT": [ 50, 2, 8 ]

network:
  default: network/pretrain.yaml

  # overwrites
  # ...

event_info:
  default: event_info/multi_process.yaml

  # overwrites
  # ...

resonance:
  default: resonance/standard_model.yaml

  # overwrites
  # ...