options:
  include: options/options.yaml

  # overwrites
  # ...

event_info:
  include: event_info/multi_process.yaml

  # overwrites
  # ...

resonance:
  include: resonance/standard_model.yaml

  # overwrites
  # ...