platform:
  data_parquet_dir: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/run.20250409.tiny"
  number_of_workers: 16
  resources_per_worker: {
    "CPU": 30,
    "GPU": 1,
  }
  batch_size: 8
  prefetch_batches: 2

options:
  default: options/options.yaml

  # For prediction Only
  prediction:
    # The directory where the prediction data is saved
    output_dir: "./test_output"
    # The filename of the prediction data
    filename: "prediction.pt"

  Training:
    model_checkpoint_load_path: "/global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/playground/checkpoints/best_epoch=15-v1.ckpt"
    #    pretrain_model_load_path: "/Users/avencastmini/ray_results/EveNet-Training/TorchTrainer_8685a_00000_0_2025-04-10_22-15-19/checkpoint_000000/checkpoint.ckpt"

    # Should follow the same components as your finetune model
    Components:
      Regression:
        include: false

      Assignment:
        include: true

  Dataset:
    dataset_limit: 0.002
    normalization_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/run.20250409.tiny/normalization.pt"

network:
  default: network/pretrain.yaml

event_info:
  default: event_info/multi_process.yaml

resonance:
  default: resonance/standard_model.yaml
