platform:
  data_parquet_dir: "/Users/avencastmini/PycharmProjects/EveNet/workspace/test_data/Run3_output"
  number_of_workers: 1
  resources_per_worker: {
    "CPU": 1,
    "GPU": 0,
  }
  batch_size: 128
  prefetch_batches: 1
  use_gpu: false

options:
  default: options/options.yaml

  # For prediction Only
  prediction:
    # The directory where the prediction data is saved
    output_dir: "/Users/avencastmini/PycharmProjects/EveNet/workspace/test_data/Run3_output_predict"
    # The filename of the prediction data
    filename: "prediction.pt"

    extra_save:
      - num_sequential_vectors

  Training:
    pretrain_model_load_path:  "/Users/avencastmini/PycharmProjects/EveNet/workspace/checkpoints/EveNet-20M-20250811-train=2.6601_val=2.6352.ckpt"

    # Should follow the same components as your finetune model
    Components:
      Classification:
        include: true

      Regression:
        include: false

      Assignment:
        include: false

      Segmentation:
        include: true
#        use_full_mask: true

  Dataset:
    dataset_limit: 0.0001
    normalization_file: "/Users/avencastmini/PycharmProjects/EveNet/workspace/test_data/Run3_output/normalization.pt"

network:
  default: pretrain-config/network-20M.yaml

event_info:
  default: event_info/multi_process.yaml

resonance:
  default: resonance/standard_model.yaml
