platform:
  data_parquet_dir: "/Users/avencastmini/PycharmProjects/EveNet/workspace/test_data/test_output"
  number_of_workers: 1
  resources_per_worker: {
    "CPU": 1,
    "GPU": 0,
  }
  batch_size: 128
  prefetch_batches: 1
  use_gpu: false

options:
  default: options/options.yaml

  # For prediction Only
  prediction:
    # The directory where the prediction data is saved
    output_dir: "/Users/avencastmini/PycharmProjects/EveNet/workspace/test_data/test_output"
    # The filename of the prediction data
    filename: "prediction.pt"

  Training:
    model_checkpoint_load_path: "/Users/avencastmini/ray_results/EveNet-Training/TorchTrainer_ba2cf_00000_0_2025-04-26_16-07-02/checkpoint_000001/checkpoint.ckpt"
    #    pretrain_model_load_path: "/Users/avencastmini/ray_results/EveNet-Training/TorchTrainer_8685a_00000_0_2025-04-10_22-15-19/checkpoint_000000/checkpoint.ckpt"

    # Should follow the same components as your finetune model
    Components:
      Regression:
        include: false

      Assignment:
        include: true

  Dataset:
    dataset_limit: 0.005
    normalization_file: "/Users/avencastmini/PycharmProjects/EveNet/workspace/test_data/test_output/normalization.pt"

network:
  default: network/pretrain.yaml

event_info:
  default: event_info/multi_process.yaml

resonance:
  default: resonance/standard_model.yaml
