platform:
  data_parquet_dir: "/pscratch/sd/t/tihsu/database/EveNet/ttZ"
  number_of_workers: 4
  resources_per_worker: {
    "CPU": 30,
    "GPU": 1,
  }
  batch_size: 4096
  prefetch_batches: 2

wandb:
  project: "Pretrain-tiny"
  entity: "ytchou97-university-of-washington"
  name: "Pretrain"
  tags: [ "Pretrain", "Parquet", "NERSC", "Multi-Node" ]

options:
  default: options/options.yaml

  # overwrites
  Training:
    epochs: 40
    model_checkpoint_save_path: "/pscratch/sd/t/tihsu/database/EveNet/ttZ/checkpoints"
    model_checkpoint_load_path: null

    Components:
      Regression:
        include: false

      Assignment:
        include: true
        detection_loss_scale: 1.0
  Dataset:
    dataset_limit: 1.0
    normalization_file: "/pscratch/sd/t/tihsu/database/EveNet/ttZ/normalization.pt"

network:
  default: network/pretrain_tiny.yaml

  # overwrites
  # ...

event_info:
  default: event_info/single_process.yaml

  # overwrites
  # ...

resonance:
  default: resonance/standard_model.yaml

  # overwrites
  # ...
