Training:
  epochs: 100

  model_checkpoint_save_path: "."
  model_checkpoint_load_path: null


  learning_rate: &lr 0.000015
  learning_rate_factor: &lr_factor 1.0
  learning_rate_warm_up_factor: &lr_warm 1.0
  weight_decay: 1e-3
  decoupled_weight_decay: true

  Components:
    GlobalEmbedding:
      learning_rate: *lr
      optimizer_group: "body" # learning rate based on the first component
      freeze:
        type: none # ['partial', 'full', 'none', 'random']
        partial_freeze_components: [ ]
        random_freeze_fraction: 0.0

    PET:
      learning_rate: *lr
      optimizer_group: "body"
      freeze:
        type: none # ['partial', 'full', 'none', 'random']
        partial_freeze_components: [ ]
        random_freeze_fraction: 0.0

    ObjectEncoder:
      learning_rate: *lr
      optimizer_group: "object_encoder"
      freeze:
        type: none # ['partial', 'full', 'none', 'random']
        partial_freeze_components: [ ]
        random_freeze_fraction: 0.0

    Classification:
      learning_rate: *lr
      optimizer_group: "classification"
      loss_scale: 1.0 # loss coefficient
      include: true # whether to build in network
      freeze:
        type: none # ['partial', 'full', 'none', 'random']
        partial_freeze_components: [ ]
        random_freeze_fraction: 0.0

    Regression:
      learning_rate: *lr
      optimizer_group: "regression"
      loss_scale: 1.0 # loss coefficient
      include: true # whether to build in network
      freeze:
        type: none # ['partial', 'full', 'none', 'random']
        partial_freeze_components: [ ]
        random_freeze_fraction: 0.0

    Assignment:
      learning_rate: *lr
      optimizer_group: "assignment"
      assignment_loss_scale: 1.0
      detection_loss_scale: 1.0
      include: false # whether to build in network
      freeze:
        type: none # ['partial', 'full', 'none', 'random']
        partial_freeze_components: [ ]
        random_freeze_fraction: 0.0


Dataset:
  dataset_limit: 1.0
  normalization_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/normalization_files/PreTrain_norm.pkl"
  train_validation_split: 0.7
