Dataset:
  balance_classifications: false
  balance_file:  "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/normalization_files/PreTrain_balance.pkl"
  balance_file_save_path: null
  balance_jets: false
  balance_particles: false
  dataset_limit: 1.0
  dataset_randomization: 0
  event_info_file: null
  limit_to_num_jets: 0
  normalization_file: "/pscratch/sd/a/avencast/Event_Level_Analysis/Pretrain_Parquet/normalization_files/PreTrain_norm.pkl"
  normalization_file_save_path: null
  normalize_features: true
  partial_events: false
  portion_for_balance: 1.0
  portion_for_statistics: 1.0
  resonance_info_file: null
  testing_file: null
  train_validation_split: 0.95
  training_file: null
  validation_file: null
Misc:
  trial_output_dir: ./test_output
  trial_time: ''
  usable_gpus: ''
  verbose_output: true
Network:
  PET_drop_probability: 0.0
  PET_dropout: 0.0
  PET_layer_scale: true
  PET_layer_scale_init: 1.0e-05
  PET_num_heads: 4
  PET_num_layers: 8
  PET_talking_head: false
  diff_resnet_nlayer: 3
  diff_sub_resnet_nlayer: 2
  diff_transformer_nlayer: 2
  enable_local_embedding: true
  feature_drop: 0.2
  hidden_dim: 128
  initial_embedding_dim: 16
  initial_embedding_skip_connections: true
  linear_activation: GELU
  linear_block_type: GRU
  linear_prelu_activation: true
  local_Krank: 2
  local_point_index:
    - 2
    - 3
  masking: Filling
  normalization: LayerNorm
  num_attention_heads: 4
  num_branch_embedding_layers: 4
  num_branch_encoder_layers: 4
  num_classification_layers: 1
  num_embedding_layers: 10
  num_encoder_layers: 4
  num_feature_keep: 0
  num_jet_embedding_layers: 0
  num_jet_encoder_layers: 0
  combinatorial_scale: 0.0
  num_local_layer: 3
  num_regression_layers: 1
  position_embedding_dim: 32
  skip_connections: true
  split_symmetric_attention: true
  time_fprojection_dim: 64
  transformer_activation: gelu
  transformer_dim: 128
  transformer_dim_scale: 2.0
  transformer_type: Gated
Training:
  balance_losses: true
  combine_pair_loss: min
  detection_loss_scale: 0.0
  dropout: 0.0
  epochs: 100
  fine_tune: false
  focal_gamma: 0.0
  generation_loss_scale: 0.0
  gradient_clip: 0.0
  kl_loss_scale: 0.0
  l2_penalty: 0.0
  learning_rate: 0.001
  learning_rate_cycles: 0
  learning_rate_factor: 1.0
  learning_rate_warmup_epochs: 1.0
  mask_sequence_vectors: true
  num_gpu: 1
  num_node: 1
  optimizer: AdamW
  classification_loss_scale: 1.0
  regression_loss_scale: 1.0
  feature_generation_loss_scale: 0.0
  assignment_loss_scale: 1.0
nMaxJet: 10
