platform:
  data_parquet_dir: "/pscratch/sd/t/tihsu/database/EveNet-AnomalyDetection/EveNetInput/SB"
  number_of_workers: 1
  resources_per_worker: {
    "CPU": 1,
    "GPU": 1,
  }
  batch_size: 1024
  prefetch_batches: 2

wandb:
  project: "anomaly-detection"
  entity: "ytchou97-university-of-washington"
  name: "toy-model"
  tags: [ "Pretrain", "Parquet", "NERSC", "Multi-Node" ]

options:
  default: options.yaml

  # overwrites
  Training:
    epochs: 10
    model_checkpoint_save_path: "/pscratch/sd/t/tihsu/database/EveNet-AnomalyDetection/EveNetInput/SB-debug"
    model_checkpoint_load_path: null

    pretrain_model_load_path: null
    diffusion_every_n_epochs: 1 # how often to run diffusion
    diffusion_every_n_steps: 1

    Components:
      GlobalGeneration:
        include: true
      EventGeneration:
        include: false

  Dataset:
    dataset_limit: 0.01
    normalization_file: "/pscratch/sd/t/tihsu/database/EveNet-AnomalyDetection/EveNetInput/SB/normalization.pt"

network:
  default: network.yaml

  # overwrites
  # ...

event_info:
  default: event_info.yaml

  # overwrites
  # ...

resonance:
  default: resonance.yaml

  # overwrites
  # ...
