# ---------------------------------------------------
# REQUIRED - INPUTS - List all inputs to SPANet here.
# ---------------------------------------------------
INPUTS:
  # -----------------------------------------------------------------------------
  # REQUIRED - SEQUENTIAL - inputs which can have an arbitrary number of vectors.
  # -----------------------------------------------------------------------------
  SEQUENTIAL:
    Source:
      mass: log_normalize
      pt: log_normalize
      eta: normalize

      atanh_sin_phi: normalize
      atanh_cos_phi: normalize

      qtag: none
      btag: none
      etag: none
      utag: none

  # ---------------------------------------------------------------------
  # REQUIRED - GLOBAL - inputs which will have a single vector per event.
  # ---------------------------------------------------------------------
  GLOBAL:
    Conditions:
      met: log_normalize
      sumet: log_normalize
      sin_phi: normalize
      cos_phi: normalize


# ----------------------------------------------------------------------
# REQUIRED - EVENT - Complete list of resonance particles and daughters.
# ----------------------------------------------------------------------
EVENT:

  TTH:
    t1:
      - b
      - l

    t2:
      - b
      - q1
      - q2

    h:
      - b1
      - b2


# ---------------------------------------------------------
# REQUIRED KEY - PERMUTATIONS - List of valid permutations.
# ---------------------------------------------------------
PERMUTATIONS:

  TTH:
    ht:
      - [ q1, q2 ]
    h:
      - [ b1, b2 ]


# ------------------------------------------------------------------------------
# REQUIRED - REGRESSIONS - List of desired features to regress from observables.
# ------------------------------------------------------------------------------
REGRESSIONS:
  EVENT:
    - neutrino_pz
    - neutrino_px
    - neutrino_py
    - neutrino_eta

# -----------------------------------------------------------------------------
# REQUIRED - REGRESSIONS - List of desired classes to predict from observables.
# -----------------------------------------------------------------------------
CLASSIFICATIONS:
  EVENT:
    - signal

CLASSLABEL:
  EVENT:
    signal:
      - [ TTH ]

PARTICLE_PROPERTIES:
  - Mass
  - Spin
  - nProduct_BJet
  - nProduct_Jet
  - nProduct_Lepton
  - Product_LeptonCharge

GENERATIONS:
  Conditions: {}