working_dir: /global/homes/t/tihsu/EveNet
spanet_dir: /global/homes/t/tihsu/SPANet
train_yaml: train.yaml
predict_yaml: predict.yaml
process_json: process.json
stat_yml: Statistics_Test.yml
input_dir:
  - /global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/data/HAA.20250621
  - /global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/data/HAA.20250620
  - /global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/data/HAA.20250619
account: m5019
email: tihsu
time: 00:15:00
job_flavor: debug
spanet:
  project: debug