EXCLUDE:
  a_had: &a_had
    b1: null
    b2: null
    SYMMETRY: [ b1, b2 ]

QCD_2b:
  category: QCD
  process_id: 0
  diagram: { }
  total_entries: 106997052
  xsec: 125100


QCD_4b:
  category: QCD
  process_id: 0
  diagram: { }
  total_entries: 2493063
  xsec: 571.4

haa_ma60:
  category: HAA
  process_id: 1
  diagram:
    H:
      a_sixty1: *a_had
      a_sixty2: *a_had
      SYMMETRY: [ a_sixty1, a_sixty2 ]

  total_entries: 2134979
  xsec: 48.58
#    a_twenty1: *a_had
#    a_twenty2: *a_had
#    SYMMETRY: [ H/a_twenty1, H/a_twenty2 ]
  store_full_name: false
  skip_first_particle: true