# --------------------
# Resonance Type - List of valid resonance particle (w. different decay topology)
# --------------------
# --------------------
# Resonance Type - List of valid resonance particle (w. different decay topology)
# --------------------


DiObjectDecay:

  a_twenty/bb:
    Mass: 20
    Spin: 0
    nProduct_BJet: 2
    nProduct_Jet: 2
    nProduct_Lepton: 0
    Product_LeptonCharge: 0
    # this is for segmentation head, starting from 1 (0 is reserved for no decay)
    segment_tag: 1

  a_thirty/bb:
    Mass: 30
    Spin: 0
    nProduct_BJet: 2
    nProduct_Jet: 2
    nProduct_Lepton: 0
    Product_LeptonCharge: 0
    # this is for segmentation head, starting from 1 (0 is reserved for no decay)
    segment_tag: 1

  a_forty/bb:
    Mass: 40
    Spin: 0
    nProduct_BJet: 2
    nProduct_Jet: 2
    nProduct_Lepton: 0
    Product_LeptonCharge: 0
    # this is for segmentation head, starting from 1 (0 is reserved for no decay)
    segment_tag: 1

  a_sixty/bb:
    Mass: 60
    Spin: 0
    nProduct_BJet: 2
    nProduct_Jet: 2
    nProduct_Lepton: 0
    Product_LeptonCharge: 0
    # this is for segmentation head, starting from 1 (0 is reserved for no decay)
    segment_tag: 1
