event_info:
  default: event_info_MASS.yaml
network:
  default: network.yaml
options:
  Dataset:
    dataset_limit: 1.0
    normalization_file: /pscratch/sd/t/tihsu/normalization.pt
  Training:
    Components:
      Assignment:
        include: true
      Classification:
        include: true
      Segmentation:
        include: true
      GlobalGeneration:
        include: false
      ReconGeneration:
        include: false

    ProgressiveTraining:
      stages:
        - epoch_ratio: 1.0
          loss_weights:
            assignment:
              - 1.0
              - 1.0
            classification:
              - 500.0
              - 500.0
            classification-noised:
              - 0.0
              - 0.0
            generation:
              - 0.0
              - 0.0
            generation-recon:
              - 0.0
              - 0.0
            regression:
              - 0.0
              - 0.0
          name: full_training
          train_parameters:
            ema_decay:
              - 0.999
              - 0.999
            noise_prob:
              - 1.0
              - 1.0
            reco_attn_mask:
              - 0.0
              - 0.0
          transition_ratio: 0.0

    epochs: 50
    model_checkpoint_load_path: null
    model_checkpoint_save_path: /pscratch/sd/t/tihsu/model_checkpoint
    patience: 20
    pretrain_model_load_path: /pscratch/sd/t/tihsu/database/Checkpoint/20M.ckpt
  default: options.yaml
platform:
  batch_size: 2048
  data_parquet_dir: /pscratch/sd/t/tihsu
  number_of_workers: 4
  prefetch_batches: 2
  resources_per_worker:
    CPU: 30
    GPU: 1
resonance:
  default: resonance.yaml

logger:
  wandb:
    project: ExoticHiggsDecay
    entity: "ytchou97-university-of-washington"
    name: toy-model
    run_name: evenet_pretrain_20
    tags: [ "Downstream", "NERSC", "Multi-Node", "Exotic Higgs Decay", "For-paper", "Vanilla" ]
    simplified: false
  local:
    save_dir: "/pscratch/sd/t/tihsu/log"
    name: evenet
    version: "test-2"
