name: Build and Publish Python Package

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # (Optional) run tests on PRs/pushes; skip on release if you want speed
      - name: Run tests
        if: github.event_name != 'release'
        run: |
          pip install -e .[test] || true
          pytest -q || true

      - name: Build sdist and wheel
        run: python -m build

      - name: Check metadata (twine)
        run: twine check dist/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: evenet-dist
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      id-token: write   # Required for PyPI Trusted Publishing (OIDC)
      contents: read
    steps:
      - name: Download distribution artifacts
        uses: actions/download-artifact@v4
        with:
          name: evenet-dist
          path: dist

      - name: Publish to PyPI via OIDC (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
